import Head from 'next/head'
import { signOut, useSession } from "next-auth/react";


export default function Home() {
  const {status} = useSession();

  console.log('status', status)

  return (
    <main>
      <Head>
        <title>Baffle Space Games | MVP</title>
        <meta name="description" content="Generated by create next app"/>
        <link rel="icon" href="/public/favicon.ico"/>
      </Head>

      <h1 className="font-bold py-10">Hello, you are {status}</h1>
      <button onClick={() => signOut()}>Sign out</button>

    </main>
  )
}
