import Head from 'next/head'

export default function Home() {
  return (
    <main>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app"/>
        <link rel="icon" href="/public/favicon.ico"/>
      </Head>

      <h1 className="font-bold py-10">Hello</h1>
    </main>
  )
}
