import Head from 'next/head'
import { signOut } from "next-auth/react";
import Header from "@/root/components/Header";
import useUserSession from "@/root/hooks/useUserSession";


export default function Home() {
  const {userInfo} = useUserSession()

  console.log('user info', userInfo)

  return (
    <main>
      <Head>
        <title>Baffle Space Games | MVP</title>
        <meta name="description" content="Generated by create next app"/>
        <link rel="icon" href="/public/favicon.ico"/>
      </Head>

      <Header/>
      {userInfo && (
        <div className='text-center py-10'>
          <button className='bg-red-600 text-white p-3 rounded' onClick={() => signOut()}>Sign out</button>
        </div>
      )}
    </main>
  )
}
